### ISSUE TITLE
运行报错?

### ISSUE THREAD

**Issue by reuwi** [GooeyNyan/async-await-practice#1]
代码写得很6很🐮,可是我用浏览器运行的时候报错,是因为用parcel打包的问题?用webpack重新编译打包了一下,ok了

**Comment by GooeyNyan** [comment]
谢谢鼓励！

诶？
```
parcel index.html
```
会有问题么？

**Comment by reuwi** [comment]
@GooeyNyan 好吧,我不知道需要用parcel运行index.html,我以为直接浏览器运行index.html就好了😂

**Comment by GooeyNyan** [comment]
嗯嗯，么事么事😂😂😂
安利 parcel 诶，随时想折腾点小东西随手就可以写了。不用先去搞 webpack 的一堆配置。
（嗯嗯…小东西下比较方便，项目大了需求多了就难说了。）

欢迎多交流啦~
